WIP: Activity Language
ftsrg/gamma pull request #55
Opened 2021-04-11 13:50 UTC by rokkerboci

2021-11-04 17:40 UTC, grbeni requested changes
Overall, the code looks good.
We will definitely need some tests (at least for the basic functions) to make sure that the transformations work correctly and are semantic-preserving.
The integration of the activity transformation into the main workflow looks good at first glance, but we should talk about the details as we might come up with some better solutions or package organizations (we should keep these two parts as loosely coupled as possible).

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/META-INF/MANIFEST.MF
> + hu.bme.mit.gamma.activity.model,
Why is `hu.bme.mit.gamma.activity.model` duplicated?

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/ActionTransformer.xtend
> +import hu.bme.mit.gamma.statechart.lowlevel.model.InitialiseActivityAction
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/ActivityNodeTransformer.xtend
> +import hu.bme.mit.gamma.lowlevel.xsts.transformation.patterns.InputFlows
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/ActivityNodeTransformer.xtend
> +					it.actions.add(node.createRunningAssumeAction)
Previously you used `+=` (preferable) instead of `add`.

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/HierarchicalTransitionMerger.xtend
> +import hu.bme.mit.gamma.lowlevel.xsts.transformation.patterns.Nodes
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/LowlevelToXstsTransformer.xtend
> +import hu.bme.mit.gamma.activity.model.InitialNode
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/LowlevelToXstsTransformer.xtend
> +		this.optimize = false
Are you sure this is okay?

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/Trace.xtend
> +import hu.bme.mit.gamma.action.model.VariableDeclarationStatement
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.lowlevel.xsts.transformation/src/hu/bme/mit/gamma/lowlevel/xsts/transformation/XstsUtils.xtend
> +package hu.bme.mit.gamma.lowlevel.xsts.transformation
This class could be moved to `hu.bme.mit.gamma.xsts.model/src/hu/bme/mit/gamma/xsts/util`

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend
> +import hu.bme.mit.gamma.activity.model.CallActivityAction
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend
> +
Why is it empty? Add a comment

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend
> +	protected dispatch def transformDoAction(CallActivityAction action, State lowlevelState) {
Use the same parameter names if they refer to the same thing in dispatch methods: `state` vs. `lowlevelState`

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActionTransformer.xtend
> +
Why is it empty? Add a comment

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/ActivityToLowlevelTransformer.xtend
> +import hu.bme.mit.gamma.statechart.statechart.TriggerNode
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/StatechartToLowlevelTransformer.xtend
> +import hu.bme.mit.gamma.activity.model.ActivityDeclaration
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.statechart.lowlevel.transformation/src/hu/bme/mit/gamma/statechart/lowlevel/transformation/Trace.xtend
> +import hu.bme.mit.gamma.activity.model.ActivityNode
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.xsts.transformation.util/src/hu/bme/mit/gamma/xsts/transformation/util/Namings.xtend
> +import hu.bme.mit.gamma.activity.model.ActivityNode
Organize imports

2021-11-04 17:40 UTC, grbeni commented on plugins/xsts/hu.bme.mit.gamma.xsts.transformation.util/src/hu/bme/mit/gamma/xsts/transformation/util/XstsNamings.xtend
> +import hu.bme.mit.gamma.activity.model.Pin
Organize imports

2022-08-22 12:36 UTC, zavadaarmin commented
@grbeni If you have the time, please check this PR again. I have implemented the composition transformation, the lowlevel activity optimizing is yet to be done.

If possible, it would be benificial imo if that would be done in another PR, as this has become rather big :)

I have attached an example XSTS file generated from the optimized synchronous version of the spacecraft model: [Mission.txt](https://github.com/ftsrg/gamma/files/9394359/Mission.txt)

2023-12-15 06:53 UTC, closed without merging